export const keywordGroups = [
    // {
    //     title: "🔍 Bệnh lý tổng quát",
    //     items: ["nhập viện", "điều trị", "khám bệnh", "bệnh sử", "chẩn đoán"],
    // },
    {
        title: "🫁 Triệu chứng hô hấp & phổi",
        items: [
            "ho",
            "ho đàm",
            "ho khan",
            "ho ra máu",
            "khò khè",
            "khó thở",
            "thở gấp",
            "co kéo cơ hô hấp",
            "đau tăng khi hít sâu",
            "ran nổ",
            "ran rít",
            "ran ẩm",
            "phổi thô",
            "co lõm ngực",
            "giảm âm",
            "đàm trắng",
            "khạc đàm"
        ],
    },
    {
        title: "❤️ Tim mạch - Tuần hoàn",
        items: [
            "tim đều",
            "tim đều rõ",
            "mạch rõ",
            "tăng huyết áp",
            "chi ấm",

        ],
    },
    {
        title: "🌡️ Triệu chứng toàn thân",
        items: [
            "sốt",
            "sốt cao",
            "ớn lạnh",
            "chán ăn",
            "buồn nôn",
            "nôn",
            "suy kiệt",
            "mệt mỏi",
            "ăn uống kém",
            "tổng trạng gầy",
            "nhiệt độ 37 độ",
            "đau toàn thân",
            "mất sức",
            "tiêu chảy",
            "tiểu buốt",
            "không có triệu chứng",
        ],
    },
    {
        title: "🩺 Khám lâm sàng - Da niêm - Cảm giác tiếp xúc",
        items: [
            "bệnh tỉnh",
            "niêm hồng",
            "niêm hồng nhạt",
            "tiếp xúc tốt",
            "môi hồng",
            "tím môi",
            "tím tái",
            "da xanh tái",
            "khỏe mạnh",
            "sức khỏe bình thường"
        ],
    },
    {
        title: "🧍 Cơ quan nội tạng & vùng khám",
        items: [
            "bụng mềm",
            "gan lách",
            "gan lách sờ không chạm",
            "đau thượng vị",
            "đau bụng",
            "đau gan",
            "lách to",
            "tiêu chảy",
            "tiểu nhiều",
        ],
    },
    {
        title: "🧠 Thần kinh - Ý thức - Hành vi",
        items: [
            "tỉnh",
            "lơ mơ",
            "mê",
            "không đáp ứng",
            "chóng mặt",
            "yếu liệt",
            "suy nhược",
        ],
    },
    {
        title: "🦴 Cơ xương khớp - Cảm giác",
        items: [
            "đau lưng",
            "đau ngực",
            "đau cơ",
            "mỏi",
            "đau lói",
            "cứng cơ",
            "co giật"
        ],
    },
    {
        title: "🧾 Tiền sử bệnh",
        items: [
            "hen phế quản",
            "suy hô hấp",
            "phù phổi",
            "tràn dịch màng phổi",
            "tràn khí màng phổi",
            "u phổi",
            "viêm phổi",
            "xẹp phổi",
            "lao phổi",
            "covid",
            "viêm dạ dày",
            "viêm ruột",
            "viêm ruột thừa",
            "tăng huyết áp",
            "đái tháo đường",
            "copd",
            "sỏi túi mật",
            "tai biến",
            "tai biến mạch máu",
            "suy thận",
            "suy tim",
            "xuất huyết",
            "bệnh phổi mạn tính"
        ],
    }
];
